### ISSUE TITLE
Dockerfile feedback

### ISSUE THREAD

**Issue by Emily-Jiang** [majguo/liberty-aad-oidc#1]
Please use the following [best practices](https://github.com/openliberty/ci.docker#building-an-application-image) for authoring Dockerfile.

The key is to run configure.sh.

You can find Open Liberty's docker images from [here](https://hub.docker.com/r/openliberty/open-liberty).

WebSphere Liberty [docker image](https://hub.docker.com/_/websphere-liberty) 

Please demonstrate both Java8 and Java11 versions.

**Comment by majguo** [comment]
Thanks for the comments. The issue is fixed in https://github.com/majguo/liberty-aad-oidc/pull/5.

**Comment by majguo** [comment]
Closing the issue as it's already fixed in #5.
