### ISSUE TITLE
Blog post review comments

### ISSUE THREAD

**Issue by gcharters** [majguo/liberty-aad-oidc#14]
Just some minor comments:

1. There is a switch between Java EE and Jakarta EE without any explanation.  I think it's an opportunity to promote Jakarta EE as the future of Java EE.
2. "only user's with role" -> "only users with role"
3. This seemed a little weird - "with the AtInject standard @Inject annotations"
4. Could mention that this is to be done in AAD.  It's not clear until you get to the end of the paragraph - "To add a groups claim into the ID token, you will need to create a group with type as Security and add one or more members. "

**Comment by lauracowen** [comment]
Minor other things:

- make "id" into "ID" when used in a sentence (as opposed to when talking about the literal attribute name). Or if they're intended to be the attribute names, maybe monospace them?
- "&" to "and" throughout
- Is there a reason why "feature" in "(openidConnectClient-1.0) **feature** to authenticate a user" is in bold?
- Maybe break the paragraph under the first example before "The userIdentityToCreateSubject parameter..."? It just makes it easier to read the bit about that parameter.
- I would highlight literal values in monospace too, eg "i.e. setting the `defaultSSLConfig` `trustDefaultCerts` value to `true`".

**Comment by m-reza-rahman** [comment]
Fixed. Please re-open if needed.
